# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2948ced41a315a641560b002b373e3c6057b0a758cd5137f4bcfb4c1c27dedac318bb8beda012b2673f610de27df402eacd0d202cac7c0ccc1cb88c3db27a5f7

test:
  secret_key_base: d5cead6ef43c55593515923a57ef2e03fbe7cacf8f09f469c0917cb970c4d532ad71b2058a5e846836315753ed57d155d42b34ca2de417c4ed9a37be93e19695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
